# /etc/modprobe.d/60-telemetry.conf

# Input Injection Surfaces
#========================
install hidraw /bin/true

# DMA / Observation
#========================
install firewire_core /bin/true
install firewire_ohci /bin/true
install firewire_net /bin/true
install thunderbolt /bin/true

# Intel Platform Monitoring
#========================
install intel_vsec /bin/true
install pmt_class /bin/true
install pmt_crashlog /bin/true
install pmt_discovery /bin/true
install pmt_telemetry /bin/true

# Intel ME Interface
#========================
install mei-vsc /bin/true
install microread_mei /bin/true

# AMD Telemetry
#========================
install amd_pmf /bin/true
install amd_rapl /bin/true
install amd_sfh /bin/true
