# /etc/dnf/dnf.conf

[main]
best=False
clean_requirements_on_remove=True
deltarpm=True
fastestmirror=True
gpgcheck=True
installonly_limit=4
install_weak_deps=False
max_parrallel_downloads=16
skip_if_unavailable=True
