# /etc/dnf/dnf.conf

[main]
best=False
clean_requirements_on_remove=True
deltarpm=True
fastestmirror=True
gpgcheck=True
installonly_limit=2
install_weak_deps=False
ip_resolve=4
max_parrallel_downloads=12
obsoletes=True
protect_running_kernel=True
skip_if_unavailable=True
sslverify=True
keepcache=False
cachedir=/var/cache/dnf
logfile=/var/log/dnf.log
